target="template_release"
debug_symbols="no"
lto="thin"
arch="x86_64"
optimize="speed"

production="yes"
disable_3d="yes"
module_text_server_adv_enabled="yes"
module_text_server_fb_enabled="no"

openxr="no"      # Disables Virtual Reality/Augmented Reality stuff
minizip="no"     # Disables ZIP archive support
d3d12="yes"

module_bmp_enabled="no"
module_camera_enabled="no"
module_csg_enabled="no"
module_enet_enabled="no"
module_fbx_enabled="no"
module_gltf_enabled="no"
module_godot_physics_3d_enabled="no"
module_gridmap_enabled="no"
module_hdr_enabled="no"
module_jolt_physics_enabled="no"
module_ktx_enabled="no"
module_mobile_vr_enabled="no"
module_multiplayer_enabled="no"
module_navigation_enabled="no"
module_openxr_enabled="no"
module_tga_enabled="no"
module_upnp_enabled="no"
module_webrtc_enabled="no"
module_webxr_enabled="no"
module_xatlas_unwrap_enabled="no"
